### ISSUE TITLE
Maven build fails with non-resolvable parent pom

### ISSUE THREAD

**Issue by tkutz** [c2mon/c2mon-daq-hostmetrics#2]
Hi,

I want to understand how DAQs are implemented so I am trying to build this project from source via maven. But maven complains about a non-resolvable parent pom:

[FATAL] Non-resolvable parent POM for cern.c2mon.daq:c2mon-daq-rest:1.10.0-SNAPSHOT: Could not transfer artifact cern.c2mon.daq:c2mon-daq-parent:pom:1.10.0 from/to releases (https://repository.cern.ch/nexus/content/repositories/c2mon-releases/): Connect timed out and 'parent.relativePath' points at wrong local POM @ line 5, column 11

Is there a server down on your side, or do I need a special settings.xml file to build the sources with maven?

Also, mails to c2mon-support@cern.ch are not getting delivered.

**Comment by alkoclick** [comment]
Ping @bcopy @mbraeger @inad9300, hopefully someone will pick this up

Hi, @tkutz! I'm a former member of this team. This repo is mirrored from an internal Gitlab installation and custom `settings.xml` files are indeed commonly used. It is however possible that you can build those artifacts locally by running `maven install` on the [C2MON](https://github.com/c2mon/c2mon) project, which contains the c2mon-daq-parent repo!

**Comment by mbraeger** [comment]
Sorry for the very late reply. Next time ping us maybe also on c2mon-support@cern.ch. 

In deed you need a special settings.xml to build the repo outside of CERN.  It's now available in the Master branch.
